# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mainshowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodtypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=50)),
                ('typename', models.CharField(max_length=100)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
