# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='marketprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
