# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180821_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('u_passwd', models.CharField(max_length=32)),
                ('u_mail', models.CharField(max_length=64, unique=True)),
                ('u_sex', models.BooleanField(default=1)),
                ('u_img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
