# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180823_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='o_number',
            field=models.CharField(max_length=128),
        ),
    ]
